Buffet/Models/CheckedIn.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet.Models
{
    public class CheckedIn
    {
        //Id
        public int Id { get; set; }

        //Dato
        public DateTime Date { get; set; }

        //Værelsesnummer
        public string RoomNumber { get; set; }

        //Antal Voksne
        public int Adults { get; set; }

        //Antal Børn
        public int Children { get; set; }
    }
}

Buffet/Models/ErrorViewModel.cs
using System;

namespace Buffet.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Buffet/Models/KitchenViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Buffet.Models
{
    public class KitchenViewModel
    {
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        public IEnumerable<Reservation> Reservations { get; set; }
        public IEnumerable<CheckedIn> CheckedIns { get; set; }

        public int ExpectedChildren => Reservations.Sum(r => r.Children);
        public int ExpectedAdults => Reservations.Sum(r => r.Adults);
        public int ExpectedGuests => ExpectedChildren + ExpectedAdults;
        public int ChildrenCheckedIn => CheckedIns.Sum(c => c.Children);
        public int AdultsCheckedIn => CheckedIns.Sum(c => c.Adults);
        public int ChildrenNotCheckedIn => ExpectedChildren - ChildrenCheckedIn;
        public int AdultsNotCheckedIn => ExpectedAdults - AdultsCheckedIn;
        public int TotalNotCheckedIn => ChildrenNotCheckedIn + AdultsNotCheckedIn;

    }
}

Buffet/Models/Reception.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet.Models
{
    public class Reception
    {
        //Id
        public int Id { get; set; }

        //Dato
        public DateTime Date { get; set; }

        //Antal Voksne
        public int Adults { get; set; }

        //Antal Børn
        public int Children { get; set; }
    }
}

Buffet/Models/Reservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet.Models
{
    public class Reservation
    {
        //Id
        public int Id { get; set; }

        //Dato
        public DateTime Date { get; set; }

        //Antal Voksne
        public int Adults { get; set; }

        //Antal Børn
        public int Children { get; set; }
    }
}

Buffet/Controllers/HomeController.cs
using Buffet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Buffet/Controllers/KitchenController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Buffet.Data;
using Buffet.Models;
using Microsoft.AspNetCore.Authorization;

namespace Buffet.Controllers
{
    public class KitchenController : Controller
    {
        ApplicationDbContext _context;

        public KitchenController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "IsKitchen")]
        public IActionResult Index()
        {
            return View(); 
        }

        [HttpPost]
        public IActionResult Details(DateTime date)
        {
            var vm = new KitchenViewModel()
            {
                Reservations = _context.Reservations.Where(r => r.Date >= date.Date && r.Date < date.Date.AddDays(1)).ToList(),
                CheckedIns = _context.CheckedIns.Where(r => r.Date >= date.Date && r.Date < date.Date.AddDays(1)).ToList(),
                Date = date
            };
            return View(vm);
        }
    }
}

Buffet/Controllers/ReceptionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Buffet.Data;
using Buffet.Models;
using Microsoft.EntityFrameworkCore;

namespace Buffet.Controllers
{
    public class ReceptionController : Controller
    {
         ApplicationDbContext _context;

        public ReceptionController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "IsReception")]
        public IActionResult Index()
        {
            return View();
        }

        // GET: Reception/Create
        [Authorize(Policy = "IsReception")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Reception/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "IsReception")]
        public async Task<IActionResult> Create([Bind("Date, Adults, Children")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), reservation); 
            }

            return View(reservation);
        }

        [Authorize(Policy = "IsReception")]
        public async Task<IActionResult> Details([Bind("Date")] CheckedIn reservation)
        {
            var date = DateTime.Today;
            var people = await _context.CheckedIns.Where(c => date.Date <= c.Date && c.Date < date.Date.AddDays(1)).ToListAsync();
            
            return View(people);
        }
    }
}

Buffet/Controllers/RestaurantController.cs
using Buffet.Data;
using Buffet.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet.Controllers
{
    public class RestaurantController : Controller
    {
        ApplicationDbContext _context;
        public RestaurantController(ApplicationDbContext context)
        {
            _context = context;
        }

        [Authorize(Policy = "IsRestaurant")]
        public IActionResult Index()
        {
            return View();
        }

        // GET: Restaurant/Create
        [Authorize(Policy = "IsRestaurant")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Restaurant/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "IsRestaurant")]
        public async Task<IActionResult> Create([Bind("Date,RoomNumber,Adults,Children")] CheckedIn checkedIn)
        {
            if (ModelState.IsValid)
            {
                _context.Add(checkedIn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), checkedIn); 
            }

            return View(checkedIn);
        }
    }
}

Buffet/Controllers/RestaurentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Buffet.Controllers
{
    public class RestaurantController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Buffet/Pages/Reception/Details.cshtml
@model IEnumerable<Buffet.Models.CheckedIn>

@{
    ViewData["Title"] = "Reception";
}

<h1>Following table shows who's eaten brekkie today </h1>
<table class="table">
    <thead>
    <tr>
        <th>
            RoomNumber
        </th>
        <th>
            Children checked in
        </th>
        <th>
            Adults checked in
        </th>
    </tr>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Children)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adults)
                </td>
            </tr>
        }
    </tbody>
</table>

Buffet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is the Home page for our Buffet web application.</p>

    <p>To see the tab for Reception, log in with: </p>
    <ul>Admin User: Recep@null</ul>
    <ul>Pass: Password123!</ul>

    <p>To see the tab for Restaurant, log in with: </p>
    <ul>Admin User: Restau@null</ul>
    <ul>Pass: Password123!</ul>

    <p>To see the tab for Kitchen, log in with: </p>
    <ul>Admin User: Kitch@null</ul>
    <ul>Pass: Password123!</ul>
</div>

Buffet/Views/Kitchen/Details.cshtml
@model Buffet.Models.KitchenViewModel
@{
    ViewData["Title"] = "Kitchen";
}

<div class="container">
    <div class="row">
        <form asp-action="Details" method="post">
            <input type="hidden" asp-for="Date.Date" />
            <input type="submit" value="Refresh" class="btn btn-primary" />
        </form>
    </div>
    <div class="row">
        <div class="col-md-4">
            <input asp-for="Date" class="form-control"/>
        </div>
        <div class="col-md-4">
            <span asp-validation-for="Date" class="text-danger"/>
        </div>
        <div class="col-md-4">
            <input type="submit" value="Go" class="btn btn-secondary"/>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Total expected guests
                </strong>
                @Model.ExpectedGuests
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Expected children
                </strong>
                @Model.ExpectedChildren
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Expected adults
                </strong>
                @Model.ExpectedAdults
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Adults checked in
                </strong>
                @Model.AdultsCheckedIn
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Children checked in
                </strong>
                @Model.ChildrenCheckedIn
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Total guests not checked in
                </strong>
                @Model.TotalNotCheckedIn
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Children not checked in
                </strong>
                @Model.ChildrenNotCheckedIn
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md" align="left">
            <p>
                <strong>
                    Adults not checked in
                </strong>
                @Model.AdultsNotCheckedIn
            </p>
        </div>
    </div>
</div>

Buffet/Views/Kitchen/Index.cshtml
@model Buffet.Models.KitchenViewModel

@{
    ViewData["Title"] = "Kitchen";
}


<div class="row">
    <div class="col-md-3">
        <form asp-action="Details">
            <div asp-validation-summary="ModelOnly" class="text-danger" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"> Choose a date </label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger" />
                <input type="submit" value="Go" class="btn btn-secondary" />
            </div>
        </form>
    </div>
</div>

Buffet/Views/Reception/Create.cshtml
@model Buffet.Models.Reservation

@{
    ViewData["Title"] = "Reception";
}
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <form asp-action="Create" asp-controller="Reception">
                <div asp-validation-summary="ModelOnly" class="text-danger" />
                <div class="form-group">
                    <label asp-for="Date" class="control-label" > Insert date for breakfast</label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger" />
                </div>
                <div class="form-group">
                    <label asp-for="Adults" class="control-label" > How many adults? </label>
                    <input asp-for="Adults" class="form-control" />
                    <span asp-validation-for="Adults" class="text-danger" />
                </div>
                <div class="form-group">
                    <label asp-for="Children" class="control-label" > How many bebe? </label>
                    <input asp-for="Children" class="form-control" />
                    <span asp-validation-for="Children" class="text-danger" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-secondary" />
                </div>
            </form>
        </div>+
        
        

    </div>
</div>

Buffet/Views/Reception/Details.cshtml
@model IEnumerable<Buffet.Models.CheckedIn>
@{
    ViewData["Title"] = "Reception";
}


<h1>Following table shows who's eaten brekkie today </h1>
<table class="table">
    <thead>
        <tr>
            <th>
                RoomNumber
            </th>
            <th>
                Children checked in
            </th>
            <th>
                Adults checked in
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RoomNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adults)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Children)
                </td>
            </tr>
        }
    </tbody>
</table>

Buffet/Views/Reception/Index.cshtml
@model Buffet.Models.Reservation

@{
    ViewData["Title"] = "Reception";
}

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <form asp-action="Create" asp-controller="Reception">
                <div asp-validation-summary="ModelOnly" class="text-danger" />
                <div class="form-group">
                    <h3> Create a new reservation</h3>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"> Insert date for breakfast</label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger" />
                </div>
                <div class="form-group">
                    <label asp-for="Adults" class="control-label"> How many adults? </label>
                    <input asp-for="Adults" class="form-control" />
                    <span asp-validation-for="Adults" class="text-danger" />
                </div>
                <div class="form-group">
                    <label asp-for="Children" class="control-label"> How many children? </label>
                    <input asp-for="Children" class="form-control" />
                    <span asp-validation-for="Children" class="text-danger" />
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-secondary" />
                </div>
            </form>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-lg-6">
            <form asp-action="Details">
                <div class="form-group">
                    <h3> View who is eating breakfast today</h3>
                </div>
                <div>
                    <input type="submit" value="Go" class="btn btn-secondary" />
                </div>
            </form>
        </div>
    </div>
</div>

Buffet/Views/Restaurant/Create.cshtml
@model Buffet.Models.CheckedIn

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>CheckedIn</h4>
<hr />
<div class="row">
    <div class="col-sm-4">
        <form asp-action="Create" asp-controller="Restaurant">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomNumber" class="control-label"></label>
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adults" class="control-label"></label>
                <input asp-for="Adults" class="form-control" />
                <span asp-validation-for="Adults" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Children" class="control-label"></label>
                <input asp-for="Children" class="form-control" />
                <span asp-validation-for="Children" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Buffet/Views/Restaurant/Index.cshtml
@model Buffet.Models.CheckedIn

@{
    ViewData["Title"] = "Index";

}

<div class="container">
    <div class="row">
        <div class="col-ms-4">
            <form asp-action="Create" asp-controller="Restaurant">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="RoomNumber" class="control-label"></label>
                    <input asp-for="RoomNumber" class="form-control" />
                    <span asp-validation-for="RoomNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Adults" class="control-label"></label>
                    <input asp-for="Adults" class="form-control" />
                    <span asp-validation-for="Adults" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Children" class="control-label"></label>
                    <input asp-for="Children" class="form-control" />
                    <span asp-validation-for="Children" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-secondary" />
                </div>
            </form>
        </div>00000
    </div>
</div>
    

Buffet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Buffet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Buffet</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.HasClaim("Reception", "Yes"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reception" asp-action="Index">Reception</a>
                            </li>
                        }
                        @if (User.HasClaim("Restaurant", "Yes"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Index">Restaurant</a>
                            </li>
                        }
                        @if (User.HasClaim("Kitchen", "Yes"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Kitchen" asp-action="Index">Kitchen</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Buffet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>